SELECT 
    CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM 
    USED_GOODS_FILE f
JOIN 
    USED_GOODS_BOARD b ON f.BOARD_ID = b.BOARD_ID
WHERE 
    b.VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)  -- 조회수가 가장 높은 게시물
ORDER BY 
    f.FILE_ID DESC;  -- 파일 ID 기준 내림차순 정렬